version: "3.7"

services:
  backend:
    container_name: hm-backend
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - films:/films
    networks:
      - hm-network
    environment:
      DD_DB_HOST: db
    command: /server
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: hm-frontend
    ports:
      - 3000:3000
    links:
      - backend

  converter:
    container_name: hm-converter
    build: ./converter
    command: go run converter.go
    ports:
      - "8002:8002"
#    volumes:
#      - convert
    networks:
      - hm-network
    environment:
      DD_DB_HOST: db
    depends_on:
      - db

  db:
    container_name: hm-db
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    networks:
      - hm-network
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: hm
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_data:
  films:

networks:
  hm-network:
    driver: bridge